### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by hfelashry** [OvernodeProjets/Fixed-Palladium#1]
Hello guys! 

i hope this message finds you guys well, i am writing this to ask about contributing.

I am a beginner programmer and i am looking for projects to contribute to and i was wondering if i can contribute to fixed-palladium? if so, please add me on discord ***rechanting*** to talk.

Thank you

**Comment by achul123** [comment]
you don't accept friend requests

**Comment by achul123** [comment]
add me : achul123 or [discord](https://overnode.fr/discord)
