### ISSUE TITLE
AFK page doesnt seem to work.

### ISSUE THREAD

**Issue by NaTDeveloper** [OvernodeProjets/Fixed-Palladium#3]

**Comment by achul123** [comment]
its work its just you, check your nginx server

**Comment by achul123** [comment]
![{2CC47D17-2DDE-4C49-9957-FF0BE7622D87}](https://github.com/user-attachments/assets/38e9926e-969c-4fdf-a630-c7ac4372f432)

**Comment by achul123** [comment]
And no proof
